#!/usr/bin/env bash
# report.sh — Sarge Report Generator
# Generates Markdown and JSON reports from assessment results

set -euo pipefail

PASS=0; WARN=0; FAIL=0; SKIP=0
OUTPUT=""
RESULTS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --pass) PASS="$2"; shift 2 ;;
    --warn) WARN="$2"; shift 2 ;;
    --fail) FAIL="$2"; shift 2 ;;
    --skip) SKIP="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    --results) RESULTS="$2"; shift 2 ;;
    *) shift ;;
  esac
done

TIMESTAMP=$(date -Iseconds)
TOTAL=$((PASS+WARN+FAIL+SKIP))
HOST=$(hostname)
OS=$(lsb_release -sd 2>/dev/null || uname -a)

# Markdown report
if [[ -n "$OUTPUT" ]]; then
  cat > "${OUTPUT}.md" << MDEOF
# Sarge Gap Analysis Report
**Oscar Six Security LLC**

| Field | Value |
|---|---|
| Date | ${TIMESTAMP} |
| Host | ${HOST} |
| OS | ${OS} |
| Total Controls Assessed | ${TOTAL} |
| ✅ PASS | ${PASS} |
| ⚠️ WARN | ${WARN} |
| ❌ FAIL | ${FAIL} |
| ⏭️ SKIP | ${SKIP} |

## Results

$(echo "$RESULTS" | sed 's/^PASS|/✅ /; s/^WARN|/⚠️ /; s/^FAIL|/❌ /; s/^SKIP|/⏭️ /')

---
*Generated by Sarge v0.1.0 — https://github.com/oscarsixsecurity/sarge*
MDEOF

  # JSON report
  cat > "${OUTPUT}.json" << JSONEOF
{
  "sarge_version": "0.1.0",
  "assessment_date": "${TIMESTAMP}",
  "host": "${HOST}",
  "os": "${OS}",
  "summary": {
    "total": ${TOTAL},
    "pass": ${PASS},
    "warn": ${WARN},
    "fail": ${FAIL},
    "skip": ${SKIP}
  },
  "results": [
$(echo "$RESULTS" | while IFS='|' read -r status detail; do
    echo "    {\"status\": \"${status}\", \"detail\": \"${detail}\"},"
  done | sed '$ s/,$//')
  ]
}
JSONEOF
fi
