#!/usr/bin/env bash
# rollback-ubuntu.sh — thin wrapper around a per-run rollback.sh
# Validates the backup dir is intact and prompts for confirmation before
# applying. Generated by scripts/backup-ubuntu.sh.
#
# Usage:
#   ./scripts/rollback-ubuntu.sh --backup-dir ~/.sarge/runs/<id>/backup
#   ./scripts/rollback-ubuntu.sh --backup-dir <dir> --unattended
#   ./scripts/rollback-ubuntu.sh --run-id <id>

set -uo pipefail

BACKUP_DIR=""
RUN_ID=""
UNATTENDED=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --backup-dir|-BackupDir) BACKUP_DIR="${2:-}"; shift 2 ;;
    --run-id)                RUN_ID="${2:-}"; shift 2 ;;
    --unattended)            UNATTENDED=1; shift ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      echo "[Sarge rollback] Unknown arg: $1" >&2
      exit 2
      ;;
  esac
done

if [[ -z "$BACKUP_DIR" && -n "$RUN_ID" ]]; then
  BACKUP_DIR="$HOME/.sarge/runs/$RUN_ID/backup"
fi

if [[ -z "$BACKUP_DIR" ]]; then
  # No explicit choice — pick the newest run with a backup/.
  if compgen -G "$HOME/.sarge/runs/*/backup/rollback.sh" >/dev/null; then
    # shellcheck disable=SC2012
    BACKUP_DIR="$(ls -1dt "$HOME"/.sarge/runs/*/backup 2>/dev/null | head -1)"
    echo "[Sarge rollback] Defaulting to newest backup: $BACKUP_DIR"
  else
    echo "[Sarge rollback] No backup dir specified and none found under ~/.sarge/runs/." >&2
    echo "Usage: $0 --backup-dir <dir> | --run-id <id>" >&2
    exit 2
  fi
fi

# --- validate ---------------------------------------------------------------
if [[ ! -d "$BACKUP_DIR" ]]; then
  echo "[Sarge rollback] Not a directory: $BACKUP_DIR" >&2
  exit 2
fi

required=(rollback.sh summary.md)
missing=()
for f in "${required[@]}"; do
  [[ -e "$BACKUP_DIR/$f" ]] || missing+=("$f")
done
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "[Sarge rollback] Backup directory is incomplete. Missing: ${missing[*]}" >&2
  echo "  (Look for $BACKUP_DIR)" >&2
  exit 3
fi

echo "[Sarge rollback] Backup directory: $BACKUP_DIR"
echo "[Sarge rollback] Summary:"
sed 's/^/    /' "$BACKUP_DIR/summary.md" | head -30
echo ""

if [[ $UNATTENDED -ne 1 ]]; then
  read -r -p "Apply rollback now? This restores /etc files, ufw, audit, services. [y/N] " confirm
  case "$confirm" in
    y|Y|yes|YES) ;;
    *) echo "[Sarge rollback] Aborted."; exit 0 ;;
  esac
fi

exec bash "$BACKUP_DIR/rollback.sh"
